### PR TITLE
types: fix args typing issue with custom events

### PR DESCRIPTION
**Pull request by FlorianV85**
``unknown[]`` prevents typing on custom events arguments. I suggest replacing with ``any[]`` to fix this

### CODE REVIEW

**Comment by Yiin** [comment]
Please provide repro code, I'm using those events extensively and can't reproduce.

**Comment by FlorianV85** [comment]
Just typing your custom event callback arguments. In TS, ``unknown`` type can only be ``any`` or ``unknown``, so it's impossible to type arguments in this case.

```typescript
// Causes a TS error because with unknown[] the type unknown or any is expected
alt.Events.on('myCustomEvent', (myArg: string, mySecondArg: number) => {
   alt.log('test'); 
});
```

```
S2769: No overload matches this call.   
Overload 1 of 2, '(eventName: never, callback: CustomEventCallback<never>): ScriptEventHandler', gave the following error.     

Argument of type 'string' is not assignable to parameter of type 'never'.  

Overload 2 of 2, '(eventName: "myCustomEvent", callback: CustomEventCallback<unknown[]>): ScriptEventHandler', gave the following error.     

Argument of type '(myArg: string, mySecondArg: number) => void' is not assignable to parameter of type 'CustomEventCallback<unknown[]>'.       Types of parameters 'myArg' and 'params' are incompatible.         

Type 'unknown' is not assignable to type 'string'.
```

**Comment by Yiin** [comment]
use provided interface if you know the type, otherwise use `if (typeof myArg === "string")` to narrow down the type. Just because you type it inside handler, doesn't mean the value will be of this type. Typescript is for preventing those issues. Extending the interface does exactly that.

**Comment by Yiin** [comment]
```ts

declare module "@altv/server" {
  namespace Events {
    interface CustomServerEvent {
      myCustomEvent(myArg: string, mySecondArg: number): void;
    }
  }
}
```

**Comment by FlorianV85** [comment]
Huum, true! I didn't see the v2 module types like that, that's fine.

**Pull request closed without merging**
